### ISSUE TITLE
opening bracket should be valid in non sections ( e.g. passwords)

### ISSUE THREAD

**Issue by Mastercorp** [QEDK/configparser-rs#14]
In general, there is the possibility that passwords could contain some special characters like [ and ]. Therefore you will get an error, if the value contains [. Error: Found opening bracket for section name but no closing bracket.
Would be great to handle such cases.
on line 259 in ini.rs : match trimmed.find('[') {
Wouldnt it be enough to just check the position of the first [ ? Since you trim the line anyway, only check for a closing bracket if it is at position 0.
Or was there a different usecase in mind i havent thought off?

**Comment by QEDK** [comment]
Makes sense, the other use-case can be like:
```ini
comment here except no comment symbol[header]
```
Also currently, we prioritize it something like:
1. Check for comments
2. Trim line
3. Check for header
4. Finally check for KV

I feel making this change would be kind of a Pandora's box, like is this a key value or a section header? `key=[section]` The current API has already defined it to be a header, so this would have to be a breaking change. We could probably resolve this by simply prioritizing 4 over 3, but I would appreciate more community input before doing so.

**Comment by Mastercorp** [comment]
So the use-case you describe is just a wrong system.cfg from the user, since he forgot the comment symbol? In my opinion, an error would be the correct respons. One could change the config file to add the comment symbol, while for the password a config change cannot fix it.

So i would argue, the password problem is a major bug, while the comment without a comment symbol is a feature of an user avoidable problem.

**Comment by QEDK** [comment]
> 
> 
> So the use-case you describe is just a wrong system.cfg from the user, since he forgot the comment symbol? In my opinion, an error would be the correct response. One could change the config file to add the comment symbol, while for a password change way more effort is needed ( and it cannot be fixed by changing the config itself).
> 
> So i would argue, the password problem is a major bug, while the comment without a comment symbol is a feature of an user avoidable problem.
> 
> for your question: a key value or a section header? key=[section]
> its a key value, since it has = sign. If you want it to be a section, why not move it to the next line?
> key=
> [section]
> 
> You could argue if the [ sign is not at the first position after trimming, then do not search for the corresponding ]. Since its probably in a comment or part of a value (and shouldnt be a section header as a result).

Look, I'm not saying any use-case is wrong or right, although your case makes "logically" more sense - it is still a breaking change and as the author, it's my job to ensure that breaking changes can be smoothed out as possible, so give me a while to investigate and ask and I'll make a call. The password problem can also be classified as a minor bug if you just don't have brackets right? It's a subjective thing. For now, I'll delve a bit more into this and see what other kind of projects are building on this so I can identify the correct action.

**Comment by Mastercorp** [comment]
Yeah sure, take your time. Just wanted to start with a discussion about the need of it.
I maybe still don't get the use-case or purpose behind the header inside a non declared comment. Basically it is a hidden feature, since you do not even show it in the example info. Or one could say, its a not well defined area. Since in theory, i would expect that "a_valueless_key_has_None" would be also a key without a value. Since [test] is seen as a new header key, where hostname lives under. But "a_valueless_key_has_None" is not seen as None, because the header in the same line marks it as comment?
example:
[server]
a_valueless_key_has_None [test]
hostname = https://api.github.com/
so [server] has no keys under it
but [test][hostname] exists.

**Comment by QEDK** [comment]
@Mastercorp this was addressed in the latest commit, let me know if it works for you or if there's issues!
