### ISSUE TITLE
Add spacing between sections and option to add space between key and value

### ISSUE THREAD

**Issue by callensm** [QEDK/configparser-rs#17]
As it stands now (unless i'm missing an option somewhere), all sections written to a file are smashed together without the option to add a buffer/space line between them which would be nice.

Additionally, it would be nice to have an option to add a space between the key, the delimiter and the value. For examples...instead of being forced to have it written as:

```
key=value
```

have an option to do:

```
key = value
```

Both of these are aesthetic features but would be nice for writing more user-friendly files.

**Comment by QEDK** [comment]
@callensm thought about doing this but aesthetics probably came at the bottom of the to-do list. Probably a pretty-print function? Not too sure about how I would customize it though.

**Comment by QEDK** [comment]
This will be added later as an altogether new function `pretty_write` with a customizable featureset of options.

**Comment by QEDK** [comment]
> I would love this too, also with a customizable indentation size for multiline values. Do you have an estimate of when this will be released? I would be happy to help out if you don't have the time!

If you're able to, please make a PR, all contributions are welcome!

**Comment by relausen-tlg** [comment]
> > I would love this too, also with a customizable indentation size for multiline values. Do you have an estimate of when this will be released? I would be happy to help out if you don't have the time!
> 
> If you're able to, please make a PR, all contributions are welcome!

I'll give it a go - stay tuned 😄

**Comment by relausen-tlg** [comment]
PR created. I still need to sync my fork and write tests, but if you could have a look and say if you agree with my approach before I proceed then I would be a happy camper :-)

**Comment by QEDK** [comment]
Thanks @callensm for reporting @relausen-tlg for the PR, this should be done now, will be released in the next version. 🚀

**Comment by QEDK** [comment]
I’m hoping to publish the next version in the next couple of weeks,
optimistically.
