### ISSUE TITLE
Configurable line endings when serializing

### ISSUE THREAD

**Issue by roblabla** [QEDK/configparser-rs#18]
Hello,

Currently, when serializing, configparser-rs always uses unix line endings ('\n', lf). On the python side, configparser will use the appropriate line ending depending on the platform it's currently running on (crlf on windows, lf everywhere else).

I think it'd be nice if configparser would allow configuring the line endings being used, e.g. add an enum to IniDefaults to let the user chose between Lf and Crlf line endings.

**Comment by QEDK** [comment]
> Hello,
> 
> Currently, when serializing, configparser-rs always uses unix line endings ('\n', lf). On the python side, configparser will use the appropriate line ending depending on the platform it's currently running on (crlf on windows, lf everywhere else).
> 
> I think it'd be nice if configparser would allow configuring the line endings being used, e.g. add an enum to IniDefaults to let the user chose between Lf and Crlf line endings.

Good point, I will look into this a bit more and make a decision.

**Comment by QEDK** [comment]
> For us this is a needed feature, on windows we want to use CRLF line endings.
> 
> I see several possibilities for this feature:
> 
>     * do not expose any options, but change behavior to use CRLF on windows, LF anywhere else. This is a breaking change, but aligns on python's behavior afaict
> 
>     * expose a new option in IniDefault to configure the line endings. Yes it adds yet another parameters in this object, but since [Non exhaustive IniDefault #22](https://github.com/QEDK/configparser-rs/pull/22), this is not a breaking change, and adding more fields to this object does not impact the end user.
> 
>     * do both: expose an option, but by default decide depending on the platform
> 
>     * last option if you do not want to add more fields to IniDefault would be to add a `set_line_endings` to `Ini`, though it looked like you designed all parameters to be settable through the IniDefault struct.
> 
> 
> Also, #22 was done to allow adding more parameters to IniDefault without breaking the API, so not wanting to bloat IniDefault more goes a bit in another direction design-wise

I agree but line endings are low on the list of things that will cause things to break (on a modern version of Windows atleast). I think we can add something like this, similar to your first suggested option:
```
#[cfg(windows)]
const LINE_ENDING: &'static str = "\r\n";
#[cfg(not(windows))]
const LINE_ENDING: &'static str = "\n";
```
