### ISSUE TITLE
Support for multi-line values

### ISSUE THREAD

**Issue by utopiabound** [QEDK/configparser-rs#26]
*Enhancement Request*

Multi-line value support.

Either the python style [ConfigParser](https://docs.python.org/3/library/configparser.html#supported-ini-file-structure):
```ini
[Section]
Key1: Value1
Key2: Value Two
Key3: this is a haiku
    spread across separate lines
    a single value
Key4: Four
```
Or the backslash + linebreak:
```ini
[Section]
Key1: Value1
Key2: Value Two
Key3: this is a haiku \
    spread across separate lines \
    a single value
Key4: Four
```

[WikiPedia: Comparison of INI parsers](https://en.wikipedia.org/wiki/INI_file#Comparison_of_INI_parsers) which breaks down which parsers support which style of multi-line support

**Comment by jgrund** [comment]
I opted to create add simple multiline support in the [ConfigParser](https://docs.python.org/3/library/configparser.html#supported-ini-file-structure) style. 

It does not track nested indentations and will treat any leading indentation as a multiline string if `multiline` is opted into.
