### ISSUE TITLE
New release with CRLF line endings and edition 2021

### ISSUE THREAD

**Issue by vthib** [QEDK/configparser-rs#27]
Would it be possible to publish a new release? There has been two new features merged and I would love to be able to use them. Thanks!

**Comment by QEDK** [comment]
> Would it be possible to publish a new release? There has been two new features merged and I would love to be able to use them. Thanks!

Will do it in the coming week, thanks for the reminder.

**Comment by poliorcetics** [comment]
Hello, is there anything to do before a new release can be cut ?

**Comment by QEDK** [comment]
This is resolved in https://github.com/QEDK/configparser-rs/releases/tag/v3.0.1 @vthib @poliorcetics Closing now.
