### ISSUE TITLE
Panic when multiline enabled due to unwrap

### ISSUE THREAD

**Issue by ScottCUSA** [QEDK/configparser-rs#39]
configparser can cause a panic on write if multiline is enabled and value is an empty string.

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/configparser-3.0.2/src/ini.rs:421:51

**Comment by ScottCUSA** [comment]
I think, `out.push_str(lines.next().unwrap());`, could be changed to,`out.push_str(lines.next().unwrap_or(""));`, to resolve this issue.

**Comment by QEDK** [comment]
Good catch, will be fixed in the next release!
