### ISSUE TITLE
How to fetch duplicate keys in section?

### ISSUE THREAD

**Issue by jonike** [QEDK/configparser-rs#46]
Hello, Guys. I have a ini format in this sample: 

[my section] 
key=A1 
key=A2 
Key=A3 

I want to get section value with duplicate keys like: 

config.get("my section","key") will return result with :

{"key":["A1","A2","A3"]},

How can i do it? Thanks.

**Comment by QEDK** [comment]
This is not supported as the underlying storage is a HashMap, you can
instead do key = A1,A2,A3 and split by comma.
